//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Texcel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AllBilletsTravail
    {
        public string Titre { get; set; }
        public string CasTest { get; set; }
        public string Type_de_Test { get; set; }
        public string Statut { get; set; }
        public string Priorité { get; set; }
        public string Difficulté { get; set; }
        public Nullable<double> Durée { get; set; }
        public string Testeur { get; set; }
        public Nullable<System.DateTime> Date_Livraison { get; set; }
        public Nullable<int> Jours_Restant { get; set; }
    }
}
