//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Texcel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AllProjetEquipe
    {
        public string nomEquipe { get; set; }
        public string nomProjet { get; set; }
        public string nomChefProjet { get; set; }
        public string tagProjetEquipe { get; set; }
    }
}
