//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Texcel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AllSysExp
    {
        public string nomSysExp { get; set; }
        public string codeSysExp { get; set; }
        public string nomEdition { get; set; }
        public string noVersion { get; set; }
        public string commSysExp { get; set; }
        public string tagSysExp { get; set; }
    }
}
