//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Texcel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AllTesteurs
    {
        public string nomEmploye { get; set; }
        public string prenomEmploye { get; set; }
        public string tagEmploye { get; set; }
        public string nomComplet { get; set; }
    }
}
