//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Texcel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CasTest
    {
        public CasTest()
        {
            this.FicheResultat = new HashSet<FicheResultat>();
            this.Equipe = new HashSet<Equipe>();
        }
    
        public string codeCasTest { get; set; }
        public string nomCasTest { get; set; }
        public string descCasTest { get; set; }
        public string priorite { get; set; }
        public string difficulte { get; set; }
        public string codeProjet { get; set; }
        public Nullable<short> idTypeTest { get; set; }
        public Nullable<short> idJeu { get; set; }
    
        public virtual cJeu cJeu { get; set; }
        public virtual Projet Projet { get; set; }
        public virtual TypeTest TypeTest { get; set; }
        public virtual ICollection<FicheResultat> FicheResultat { get; set; }
        public virtual ICollection<Equipe> Equipe { get; set; }
    }
}
