//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Texcel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Forms
    {
        public Forms()
        {
            this.Groupe = new HashSet<Groupe>();
        }
    
        public short idForm { get; set; }
        public string nomForm { get; set; }
    
        public virtual ICollection<Groupe> Groupe { get; set; }
    }
}
