//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Texcel
{
    using System;
    using System.Collections.Generic;
    
    public partial class GenreJeu
    {
        public GenreJeu()
        {
            this.cJeu = new HashSet<cJeu>();
        }
    
        public short idGenre { get; set; }
        public string nomGenre { get; set; }
        public string descGenre { get; set; }
    
        public virtual ICollection<cJeu> cJeu { get; set; }
    }
}
