//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Texcel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Groupe
    {
        public Groupe()
        {
            this.Forms = new HashSet<Forms>();
            this.Utilisateur = new HashSet<Utilisateur>();
        }
    
        public short idGroupe { get; set; }
        public string nomGroupe { get; set; }
    
        public virtual ICollection<Forms> Forms { get; set; }
        public virtual ICollection<Utilisateur> Utilisateur { get; set; }
    }
}
