//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Texcel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbProjetE1Entities : DbContext
    {
        public dbProjetE1Entities()
            : base("name=dbProjetE1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ClassificationJeu> ClassificationJeu { get; set; }
        public virtual DbSet<EditionSysExp> EditionSysExp { get; set; }
        public virtual DbSet<GenreJeu> GenreJeu { get; set; }
        public virtual DbSet<cJeu> Jeu { get; set; }
        public virtual DbSet<Plateforme> Plateforme { get; set; }
        public virtual DbSet<SysExp> SysExp { get; set; }
        public virtual DbSet<ThemeJeu> ThemeJeu { get; set; }
        public virtual DbSet<TypePlateforme> TypePlateforme { get; set; }
        public virtual DbSet<VersionJeu> VersionJeu { get; set; }
        public virtual DbSet<VersionSysExp> VersionSysExp { get; set; }
        public virtual DbSet<Employe> Employe { get; set; }
        public virtual DbSet<Equipe> Equipe { get; set; }
        public virtual DbSet<Forms> Forms { get; set; }
        public virtual DbSet<Groupe> Groupe { get; set; }
        public virtual DbSet<Utilisateur> Utilisateur { get; set; }
        public virtual DbSet<BilletTravail> BilletTravail { get; set; }
        public virtual DbSet<CasTest> CasTest { get; set; }
        public virtual DbSet<Difficulte> Difficulte { get; set; }
        public virtual DbSet<NiveauPriorite> NiveauPriorite { get; set; }
        public virtual DbSet<cProjet> Projet { get; set; }
        public virtual DbSet<Statut> Statut { get; set; }
        public virtual DbSet<TypeTest> TypeTest { get; set; }
        public virtual DbSet<FiltreDataSource> FiltreDataSource { get; set; }
        public virtual DbSet<AllPlateforme> AllPlateforme { get; set; }
        public virtual DbSet<AllSysExp> AllSysExp { get; set; }
        public virtual DbSet<AllEquipe> AllEquipe { get; set; }
        public virtual DbSet<AllTesteurs> AllTesteurs { get; set; }
        public virtual DbSet<AllBilletTravailPriorite> AllBilletTravailPriorite { get; set; }
        public virtual DbSet<AllBilletTravailStatut> AllBilletTravailStatut { get; set; }
        public virtual DbSet<AllCasTest> AllCasTest { get; set; }
        public virtual DbSet<AllCasTestBilletTravail> AllCasTestBilletTravail { get; set; }
        public virtual DbSet<AllEmployeBilletTravail> AllEmployeBilletTravail { get; set; }
        public virtual DbSet<AllEmployeEquipe> AllEmployeEquipe { get; set; }
        public virtual DbSet<AllEmployeTypeTest> AllEmployeTypeTest { get; set; }
        public virtual DbSet<AllJeuProjet> AllJeuProjet { get; set; }
        public virtual DbSet<AllProjet> AllProjet { get; set; }
        public virtual DbSet<AllProjetCasTest> AllProjetCasTest { get; set; }
        public virtual DbSet<AllProjetClassification> AllProjetClassification { get; set; }
        public virtual DbSet<AllProjetEquipe> AllProjetEquipe { get; set; }
        public virtual DbSet<AllProjetGenre> AllProjetGenre { get; set; }
        public virtual DbSet<AllProjetTheme> AllProjetTheme { get; set; }
        public virtual DbSet<AllBilletsTravail> AllBilletsTravail { get; set; }
    }
}
