//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TexcelWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class AllCasTest
    {
        public string Code_du_cas_de_test { get; set; }
        public string Nom_du_cas_de_test { get; set; }
        public Nullable<System.DateTime> Date_de_création { get; set; }
        public Nullable<System.DateTime> Date_de_livraison { get; set; }
        public string Code_du_projet { get; set; }
        public string tagCasTest { get; set; }
    }
}
