//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TexcelWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class CasTest
    {
        public CasTest()
        {
            this.Equipe = new HashSet<Equipe>();
        }
    
        public string codeCasTest { get; set; }
        public string nomCasTest { get; set; }
        public string descCasTest { get; set; }
        public Nullable<System.DateTime> dateCreation { get; set; }
        public Nullable<System.DateTime> dateLivraison { get; set; }
        public string codeProjet { get; set; }
        public Nullable<short> idDiff { get; set; }
        public Nullable<short> idTest { get; set; }
        public Nullable<short> idResult { get; set; }
        public Nullable<short> idNivPri { get; set; }
    
        public virtual cProjet cProjet { get; set; }
        public virtual Difficulte Difficulte { get; set; }
        public virtual NiveauPriorite NiveauPriorite { get; set; }
        public virtual FicheResultat FicheResultat { get; set; }
        public virtual TypeTest TypeTest { get; set; }
        public virtual ICollection<Equipe> Equipe { get; set; }
    }
}
