//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TexcelWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClassificationJeu
    {
        public ClassificationJeu()
        {
            this.Jeu = new HashSet<Jeu>();
        }
    
        public string nomClassification { get; set; }
        public string codeClassification { get; set; }
        public string descClassification { get; set; }
    
        public virtual ICollection<Jeu> Jeu { get; set; }
    }
}
