//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TexcelWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jeu
    {
        public Jeu()
        {
            this.CasTest = new HashSet<CasTest>();
            this.VersionJeu = new HashSet<VersionJeu>();
            this.Jeu1 = new HashSet<Jeu>();
            this.Jeu2 = new HashSet<Jeu>();
            this.GenreJeu = new HashSet<GenreJeu>();
            this.Plateforme = new HashSet<Plateforme>();
            this.ThemeJeu = new HashSet<ThemeJeu>();
        }
    
        public short idJeu { get; set; }
        public string nomJeu { get; set; }
        public string developeur { get; set; }
        public string descJeu { get; set; }
        public string configMinimal { get; set; }
        public string codeClassification { get; set; }
    
        public virtual ClassificationJeu ClassificationJeu { get; set; }
        public virtual ICollection<CasTest> CasTest { get; set; }
        public virtual ICollection<VersionJeu> VersionJeu { get; set; }
        public virtual ICollection<Jeu> Jeu1 { get; set; }
        public virtual ICollection<Jeu> Jeu2 { get; set; }
        public virtual ICollection<GenreJeu> GenreJeu { get; set; }
        public virtual ICollection<Plateforme> Plateforme { get; set; }
        public virtual ICollection<ThemeJeu> ThemeJeu { get; set; }
    }
}
