//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TexcelWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Statut
    {
        public Statut()
        {
            this.BilletTravail = new HashSet<BilletTravail>();
        }
    
        public short idStatut { get; set; }
        public string nomStatut { get; set; }
        public string descStatut { get; set; }
    
        public virtual ICollection<BilletTravail> BilletTravail { get; set; }
    }
}
