//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TexcelWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysExp
    {
        public SysExp()
        {
            this.EditionSysExp = new HashSet<EditionSysExp>();
            this.Plateforme = new HashSet<Plateforme>();
        }
    
        public short idSysExp { get; set; }
        public string nomSysExp { get; set; }
        public string codeSysExp { get; set; }
    
        public virtual ICollection<EditionSysExp> EditionSysExp { get; set; }
        public virtual ICollection<Plateforme> Plateforme { get; set; }
    }
}
