//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TexcelWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblForms
    {
        public tblForms()
        {
            this.tblGroupe = new HashSet<tblGroupe>();
        }
    
        public short idForm { get; set; }
        public string nomForm { get; set; }
    
        public virtual ICollection<tblGroupe> tblGroupe { get; set; }
    }
}
