//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TexcelWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblGroupe
    {
        public tblGroupe()
        {
            this.tblForms = new HashSet<tblForms>();
            this.tblUtilisateur = new HashSet<Utilisateur>();
        }
    
        public short idGroupe { get; set; }
        public string nomGroupe { get; set; }
    
        public virtual ICollection<tblForms> tblForms { get; set; }
        public virtual ICollection<Utilisateur> tblUtilisateur { get; set; }
    }
}
