//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TexcelWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblThemeJeu
    {
        public tblThemeJeu()
        {
            this.cJeu = new HashSet<cJeu>();
        }
    
        public short idTheme { get; set; }
        public string nomTheme { get; set; }
        public string commTheme { get; set; }
    
        public virtual ICollection<cJeu> cJeu { get; set; }
    }
}
