//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TexcelWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class TypePlateforme
    {
        public TypePlateforme()
        {
            this.Plateforme = new HashSet<Plateforme>();
        }
    
        public short idTypePlateforme { get; set; }
        public string nomTypePlateforme { get; set; }
        public string descTypePlateforme { get; set; }
    
        public virtual ICollection<Plateforme> Plateforme { get; set; }
    }
}
