//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TexcelWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class TypeTest
    {
        public TypeTest()
        {
            this.CasTest = new HashSet<CasTest>();
            this.Employe = new HashSet<Employe>();
        }
    
        public short idTypeTest { get; set; }
        public string nomTypeTest { get; set; }
        public string descTypeTest { get; set; }
    
        public virtual ICollection<CasTest> CasTest { get; set; }
        public virtual ICollection<Employe> Employe { get; set; }
    }
}
