//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TexcelWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class VersionJeu
    {
        public VersionJeu()
        {
            this.CasTest = new HashSet<CasTest>();
            this.cProjet = new HashSet<cProjet>();
        }
    
        public short idVersionJeu { get; set; }
        public string nomVersionJeu { get; set; }
        public string commVersionJeu { get; set; }
        public Nullable<short> idJeu { get; set; }
    
        public virtual cJeu cJeu { get; set; }
        public virtual ICollection<CasTest> CasTest { get; set; }
        public virtual ICollection<cProjet> cProjet { get; set; }
    }
}
