//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TexcelWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class VersionSysExp
    {
        public short idVersion { get; set; }
        public string noVersion { get; set; }
        public short idEdition { get; set; }
        public string commSysExp { get; set; }
    
        public virtual EditionSysExp EditionSysExp { get; set; }
    }
}
